// Example foods, not portion, calorie or medical prescriptions.
export const foods = [
  ["Oats or whole-grain porridge", "grain", ["Breakfast"], [], true, true],
  [
    "Whole-wheat roti or brown rice",
    "grain",
    ["Lunch", "Dinner"],
    ["gluten"],
    true,
    true,
  ],
  ["Rice or millet", "grain", ["Lunch", "Dinner"], [], true, true],
  ["Whole-grain toast", "grain", ["Snack"], ["gluten"], true, true],
  ["Puffed rice", "grain", ["Snack"], [], true, true],
  ["Plain curd", "protein", ["Breakfast", "Snack"], ["dairy"], true, false],
  [
    "Chickpeas",
    "protein",
    ["Breakfast", "Snack", "Lunch", "Dinner"],
    [],
    true,
    true,
  ],
  ["Dal or rajma", "protein", ["Lunch", "Dinner"], [], true, true],
  ["Paneer", "protein", ["Lunch", "Dinner"], ["dairy"], true, false],
  ["Tofu", "protein", ["Lunch", "Dinner"], ["soy"], true, true],
  [
    "Eggs",
    "protein",
    ["Breakfast", "Snack", "Lunch", "Dinner"],
    ["egg"],
    false,
    false,
  ],
  ["Chicken or fish", "protein", ["Lunch", "Dinner"], [], false, false],
  [
    "Banana or seasonal fruit",
    "produce",
    ["Breakfast", "Snack"],
    [],
    true,
    true,
  ],
  [
    "Mixed vegetables and salad",
    "produce",
    ["Lunch", "Dinner"],
    [],
    true,
    true,
  ],
].map(([name, group, meals, allergens, vegetarian, vegan]) => ({
  name,
  group,
  meals,
  allergens,
  vegetarian,
  vegan,
}));
