export const products = [
  {
    category: "Basketball Jerseys",
    name: "Los angeles lakers city t shirt n121mt024",
    url: "https://shopthearena.com/collections/nba/products/los-angeles-lakers-city-t-shirt-n121mt024",
    retailer: "shopthearena.com",
  },
  {
    category: "Basketball Jerseys",
    name: "Nba lebron james classic t shirt nbpataw001",
    url: "https://shopthearena.com/collections/mens-t-shirts/products/nba-lebron-james-classic-t-shirt-nbpataw001",
    retailer: "shopthearena.com",
  },
  {
    category: "Basketball Jerseys",
    name: "Los angeles lakers classic crest t shirt n121mt022b",
    url: "https://shopthearena.com/collections/womens-unisex-t-shirts/products/los-angeles-lakers-classic-crest-t-shirt-n121mt022b",
    retailer: "shopthearena.com",
  },
  {
    category: "Indian Football Jerseys",
    name: "Ref=sr 1 4",
    url: "https://www.amazon.in/woopme%C2%AE-Bangalore-Football-HomeT-Shirt-Multicolour/dp/B0CNCRVFB4/ref=sr_1_4?dib=eyJ2IjoiMSJ9.O4ka4bTaWVpld_gNHWeCFBW8I8UtcFgvwl8OUCKE9COdIRLeQWoULYsjTLxypYIj2oXIBpLeyS0hSncRxBqzdUxMnEkwCZRdemIOimvD1asqA1JEcsT1T3cvG6qkcyWnBXfxpTWRs5z8MrtclQYa04HLWj-iPihY2ReZa3wRDzfconxtDympQ8TANK7vuPQeBQOEdC1MK_ZMjRzwRSdDy_t7phX2odgUYhpfu2t8W1uOckDeYrElbbnY7Dg4RSeozSOgVl4cshEhrMUVka8eYmQwfQhWZ8Uu5F6Lqc8s7IM.orPWeV8uvAl5KXQzOSLtlaGfmxjObF2xHjfWyGYza6Y&dib_tag=se&keywords=indian+football+jersey&qid=1722587178&rnid=3576079031&s=apparel&sr=1-4",
    retailer: "amazon.in",
  },
  {
    category: "Indian Football Jerseys",
    name: "Kerala blasters away jersey youth fan edition 2023 24",
    url: "https://six5six.in/products/kerala-blasters-away-jersey-youth-fan-edition-2023-24",
    retailer: "six5six.in",
  },
  {
    category: "Indian Football Jerseys",
    name: "Kerala blasters training jersey 2023 24 blue red",
    url: "https://six5six.in/products/kerala-blasters-training-jersey-2023-24-blue-red",
    retailer: "six5six.in",
  },
  {
    category: "Indian Cricket Jerseys",
    name: "India t 20 cricket world cup 2023 jersey player version",
    url: "https://fanaacs.com/products/india-t-20-cricket-world-cup-2023-jersey-player-version?_pos=4&_sid=37ff7d002&_ss=r",
    retailer: "fanaacs.com",
  },
  {
    category: "Indian Cricket Jerseys",
    name: "India t 20 cricket world cup 2024 jersey player version",
    url: "https://fanaacs.com/products/india-t-20-cricket-world-cup-2024-jersey-player-version?_pos=5&_sid=37ff7d002&_ss=r",
    retailer: "fanaacs.com",
  },
  {
    category: "Indian Cricket Jerseys",
    name: "India official mpl fan jersey",
    url: "https://bestcricketstore.com/product/india-official-mpl-fan-jersey/",
    retailer: "bestcricketstore.com",
  },
  {
    category: "Football Shoes",
    name: "Shastra 5935",
    url: "https://www.niviasports.com/products/shastra-5935",
    retailer: "niviasports.com",
  },
  {
    category: "Football Shoes",
    name: "Carbonite 6 0 football stud 1647 1",
    url: "https://www.niviasports.com/products/carbonite-6-0-football-stud-1647-1",
    retailer: "niviasports.com",
  },
  {
    category: "Football Shoes",
    name: "Spear football stud spear",
    url: "https://www.niviasports.com/products/spear-football-stud-spear",
    retailer: "niviasports.com",
  },
  {
    category: "Cricket Shoes",
    name: "Ss josh shoes for men s and boy s",
    url: "https://www.sstoncricket.com/ss-josh-shoes-for-men-s-and-boy-s.html",
    retailer: "sstoncricket.com",
  },
  {
    category: "Cricket Shoes",
    name: "Ss gutsy shoes for men s and boy s",
    url: "https://www.sstoncricket.com/ss-gutsy-shoes-for-men-s-and-boy-s.html",
    retailer: "sstoncricket.com",
  },
  {
    category: "Cricket Shoes",
    name: "Ss ultimate cricket shoes for men s and boy s",
    url: "https://www.sstoncricket.com/ss-ultimate-cricket-shoes-for-men-s-and-boy-s.html",
    retailer: "sstoncricket.com",
  },
  {
    category: "Basketball Shoes",
    name: "Elevate 3 white black pure platinum",
    url: "https://www.superkicks.in/products/elevate-3-white-black-pure-platinum",
    retailer: "superkicks.in",
  },
  {
    category: "Basketball Shoes",
    name: "Impact 4 ashen slate barely volt thunder blue",
    url: "https://www.superkicks.in/products/impact-4-ashen-slate-barely-volt-thunder-blue",
    retailer: "superkicks.in",
  },
  {
    category: "Basketball Shoes",
    name: "Impact 4 white black pure platinum",
    url: "https://www.superkicks.in/products/impact-4-white-black-pure-platinum",
    retailer: "superkicks.in",
  },
  {
    category: "Caps",
    name: "Cotton chino ball cap 643781",
    url: "https://www.ralphlauren.global/in/en/cotton-chino-ball-cap-643781.html#utm_subchannel=genericsearch&utm_source=google&utm_medium=paidsearch&utm_campaign=generic&utm_term=generic&utm_content=cid20808332152_crid706896545906_kwcaps_tidkwd-10456971_pid%7Bproductid%7D&s_kwcid=AL!6316!3!706896545906!b!!g!!caps&label=Summer-2024&gad_source=1&gclid=CjwKCAjw5Ky1BhAgEiwA5jGujm23xtKk9pYTKEHvouYAc7O5Ov5hyFjdvU2o3yDQwrHLfG5Iyq8-rRoChfYQAvD_BwE&start=1&cgid=men-caps-hats-scarves-gloves",
    retailer: "ralphlauren.global",
  },
  {
    category: "Caps",
    name: "Stretch cotton twill ball cap 100029448",
    url: "https://www.ralphlauren.global/in/en/stretch-cotton-twill-ball-cap-100029448.html#utm_subchannel=genericsearch&utm_source=google&utm_medium=paidsearch&utm_campaign=generic&utm_term=generic&utm_content=cid20808332152_crid706896545906_kwcaps_tidkwd-10456971_pid%7Bproductid%7D&s_kwcid=AL!6316!3!706896545906!b!!g!!caps&label=Summer-2024&gad_source=1&gclid=CjwKCAjw5Ky1BhAgEiwA5jGujm23xtKk9pYTKEHvouYAc7O5Ov5hyFjdvU2o3yDQwrHLfG5Iyq8-rRoChfYQAvD_BwE&start=1&cgid=men-caps-hats-scarves-gloves",
    retailer: "ralphlauren.global",
  },
  {
    category: "Caps",
    name: "Wimbledon ballperson cap 614161",
    url: "https://www.ralphlauren.global/in/en/wimbledon-ballperson-cap-614161.html#utm_subchannel=genericsearch&utm_source=google&utm_medium=paidsearch&utm_campaign=generic&utm_term=generic&utm_content=cid20808332152_crid706896545906_kwcaps_tidkwd-10456971_pid%7Bproductid%7D&s_kwcid=AL!6316!3!706896545906!b!!g!!caps&label=Summer-2024&gad_source=1&gclid=CjwKCAjw5Ky1BhAgEiwA5jGujm23xtKk9pYTKEHvouYAc7O5Ov5hyFjdvU2o3yDQwrHLfG5Iyq8-rRoChfYQAvD_BwE&start=1&cgid=men-caps-hats-scarves-gloves",
    retailer: "ralphlauren.global",
  },
  {
    category: "Equipment",
    name: "Storm",
    url: "https://www.niviasports.com/products/storm",
    retailer: "niviasports.com",
  },
  {
    category: "Equipment",
    name: "Pro touch pro touch basketball balls",
    url: "https://www.niviasports.com/products/pro-touch-pro-touch-basketball-balls",
    retailer: "niviasports.com",
  },
  {
    category: "Equipment",
    name: "Nivia cricket tennis ball heavy pack of 12",
    url: "https://www.niviasports.com/products/nivia-cricket-tennis-ball-heavy-pack-of-12",
    retailer: "niviasports.com",
  },
];
